# This is a basic workflow that is manually triggered

name: Docker Build Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
    - '**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  node-sample-build:
    runs-on: ubuntu-latest
    steps:
    - name: Source Code Checkout
      uses: actions/checkout@master
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/node-sample:master
